/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "backkey": { "creationFunction": "CreateGlassButton", "text": "Back" },
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "homekey": { "creationFunction": "CreateGlassButton", "text": "Home" },
    "hostlabel": { "text": "Host", "view": "DC.Text" },
    "image": { "view": "DC.ImageLayout" },
    "infobutton": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "infokey": { "creationFunction": "CreateGlassButton", "text": "Info" },
    "menukey": { "creationFunction": "CreateGlassButton", "text": "Menu" },
    "notify": { "text": "This is not a valid YouTube video or playlist link!", "view": "DC.Text" },
    "passlabel": { "text": "Password", "view": "DC.Text" },
    "portsshlabel": { "text": "Port SSH", "view": "DC.Text" },
    "portxbmclabel": { "text": "Port XBMC", "view": "DC.Text" },
    "send": { "creationFunction": "CreateGlassButton", "text": "Send" },
    "textentry": { "text": "Text Entry", "view": "DC.Text" },
    "textexplain": { "text": "(enter text below and click send)", "view": "DC.Text" },
    "userlabel": { "text": "User", "view": "DC.Text" }
};








